# These are supported funding model platforms

github: imhunterand # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: imhunterand # Replace with a single Patreon usernam
ko_fi: imhunterand # Replace with a single Ko-fi username
